apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: esmos
configMapGenerator:
  - name: moodle-entrypoint
    files:
      - esmos-moodle-entrypoint=moodle-entrypoint.sh
resources:
  - namespace.yaml
  - storage.yaml
  - secrets.template.yaml
  - mariadb.yaml
  - moodle.yaml
  - uptimekuma.yaml
  - networkpolicy.yaml
